name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Core
      working-directory: ./Core
      run: cargo build --verbose
    - name: Run Core tests
      working-directory: ./Core
      run: cargo test --verbose
    - name: Build egui
      working-directory: ./egui
      run: cargo build --verbose
